include: container-build/cider-ci.yml

jobs:

  build-uberjar:
    name: Build uberjar
    run_when: &ON_BRANCH_UPDATE
      any branch has been updated:
        type: branch
        include_match: ^.*$
        exclude_match: "^.*(no-ci|hotspot).*$"
    context:
      task_defaults:
        traits:
          asdf: true
        environment_variables:
          LEIHS_LENDING_DIR: "{{CIDER_CI_WORKING_DIR}}"
      tasks:
        build-uberjar:
          { include: cider-ci/task-components/uberjar.yml }

  graphql-specs:
    name: Run graphql specs
    depends_on: &SPEC_DEPS
      uberjar was built:
        type: job
        job_key: build-uberjar
        states: [passed]
    run_when: *SPEC_DEPS
    context:
      include: cider-ci/graphql-specs_job-context.yml

  feature-specs:
    name: Run feature specs
    depends_on: *SPEC_DEPS
    run_when: *SPEC_DEPS
    context:
      include: cider-ci/feature-specs_job-context.yml

  lint:
    name: Linting
    run_when: *ON_BRANCH_UPDATE
    context:
      task_defaults:
        traits:
          asdf: true
        git_options:
          submodules:
            include_match: ^.*$
        environment_variables:
          LEIHS_LENDING_DIR: "{{CIDER_CI_WORKING_DIR}}"
      tasks:
        cljfmt:
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                cd $LEIHS_LENDING_DIR
                ./bin/cljfmt check
        ruby-lint:
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                cd $LEIHS_LENDING_DIR
                ./bin/rblint
        ruby-commited:
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                cd $LEIHS_LENDING_DIR
                ./bin/check-ruby-commited

  all-ok:
    name: All Tests OK
    depends_on: &ALLOK_DEPS
      build-uberjar passed:
        type: job
        job_key: build-uberjar
        states: [passed]
      graphql-specs passed:
        type: job
        job_key: graphql-specs
        states: [passed]
      feature-specs passed:
        type: job
        job_key: feature-specs
        states: [passed]
      lint passed:
        type: job
        job_key: lint
        states: [passed]
      container-build passed:
        type: job
        job_key: container-build
        states: [passed]
      database merged to master:
        type: job
        job_key: merged-to-master
        submodule: [database]
        states: [passed]
      shared-clj merged to master:
        type: job
        job_key: merged-to-master
        submodule: [shared-clj]
        states: [passed]
    run_when: *ALLOK_DEPS
    context:
      tasks:
        all-ok:
          scripts:
            test:
              body: "exit 0"

  good-to-merge:
    name: "⚑ Good To Merge"
    priority: 99
    depends_on: &GOOD_TO_MERGE_DEPS
      all passed:
        type: job
        job_key: all-ok
        states: [passed]
    run_when: *GOOD_TO_MERGE_DEPS
    context:
      include: cider-ci/jobs/good-to-merge.yml

  merged-to-master:
    name: Merged to master
    priority: 999
    depends_on:
      master branch matches:
        type: branch
        include_match: ^master$
    run_when:
      master branch matches:
        type: branch
        include_match: ^master$
    context:
      tasks:
        merged-to-master:
          scripts:
            test:
              body: "exit 0"
